//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DACK_13_BuiXuanHieu
{
    using System;
    using System.Collections.Generic;
    
    public partial class Event
    {
        public int PromotionID { get; set; }
        public int ProductID { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public Nullable<int> LimitQuantity { get; set; }
        public double Discount { get; set; }
        public string Description { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual Promotion Promotion { get; set; }
    }
}
