//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DACK_13_BuiXuanHieu
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImportationDetail
    {
        public int ImportID { get; set; }
        public int ProductID { get; set; }
        public System.DateTime ImportDate { get; set; }
        public int ImportUnits { get; set; }
        public double UnitPrice { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
